### ISSUE TITLE
Seems incompatible with the newest ESM library

### ISSUE THREAD

**Issue by jasperhyp** [DeepGraphLearning/PEER_Benchmark#2]
Error log (when running a random single task on one GPU):

```python
Traceback (most recent call last):  
File "script/run_single.py", line 154, in <module>    
solver = build_solver(cfg, logger)  File "script/run_single.py", line 57, in build_solver    
task = core.Configurable.load_config_dict(cfg.task)  
File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/core/core.py", line 261, in load_config_dict    
v = _Configurable.load_config_dict(v)  
File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/core/core.py", line 269, in load_config_dict    
return cls(**new_config)  
File "<decorator-gen-1021>", line 2, in __init__  
File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/core/core.py", line 288, in wrapper    
return init(self, *args, **kwargs)  
File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/models/esm.py", line 55, in __init__    
_model, alphabet = self.load_weight(path, model)  
File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/models/esm.py", line 80, in load_weight    
return esm.pretrained.load_model_and_alphabet_core(model_data, regression_data)  
File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/esm/pretrained.py", line 190, in load_model_and_alphabet_core    
if model_name.startswith("esm2"):AttributeError: 'dict' object has no attribute 'startswith'
```

I guess this is because you used the ESM library before they released ESM2 in July, and they kinda changed a bit of their code structure then.  A simple fix would just be changing the args to `('esm1b', model_data, regression_data)`.

**Comment by jasperhyp** [comment]
Also, How can I only use one GPU when I have multiple?  Even if I set `os.environ['CUDA_VISIBLE_DEVICES']='0'`, it still gives me:

```python
Traceback (most recent call last):
  File "script/run_single.py", line 155, in <module>
    solver = build_solver(cfg, logger)
  File "script/run_single.py", line 78, in build_solver
    solver = core.Engine(task, train_set, valid_set, test_set, optimizer, scheduler, **cfg.engine)
  File "<decorator-gen-758>", line 2, in __init__
  File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/core/core.py", line 288, in wrapper
    return init(self, *args, **kwargs)
  File "/home/xxx/.conda/envs/plm/lib/python3.8/site-packages/torchdrug/core/engine.py", line 77, in __init__
    raise ValueError(error_msg % (self.world_size, len(gpus)))
ValueError: World size is 1 but found 4 GPUs in the argument. Did you launch with `python -m torch.distributed.launch`?
```

**Comment by ChrisAllenMing** [comment]
Thanks for pointing out the imcompatibility. We will align with the latest fair-esm library and release in new TorchDrug version.

Sure, you can change the ```engine.gpus``` to ```[0]```  (also ```[1]```, ```[2]``` or ```[3]``` case by case) in the yaml config and launch with the single-GPU command, if you just want to run with a single GPU on a multi-GPU node.

**Comment by Oxer11** [comment]
Thanks for pointing out this problem! I've fixed this bug in the latest commit on TorchDrug (https://github.com/DeepGraphLearning/torchdrug/commit/180a9a8b47fee6ab0e546db4406daf851b792c1d). Since we haven't updated the pip and conda package yet, you can try to install TorchDrug from the current source.

Hope this can help you!
